# Generated by Django 3.1.3 on 2021-02-05 17:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0008_mago_amigos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.TextField(max_length=1500, verbose_name='Cuerpo')),
                ('fecha', models.DateField(verbose_name='Fecha de creación')),
                ('remitente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('fecha', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(verbose_name='Titulo')),
                ('tipo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Tipo de evento')),
                ('descripcion', models.TextField(blank=True, max_length=1500, verbose_name='Descripción')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de creación')),
                ('fecha_evento', models.DateField(verbose_name='Fecha del evento')),
                ('aforo', models.IntegerField(verbose_name='Aforo del evento')),
                ('foto', models.ImageField(default='default.png', upload_to='', verbose_name='Foto del evento')),
                ('asistentes', models.ManyToManyField(blank=True, related_name='asistentes', to=settings.AUTH_USER_MODEL)),
                ('comentarios', models.ManyToManyField(blank=True, to='eventos.Comentario')),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creador', to=settings.AUTH_USER_MODEL)),
                ('modalidades', models.ManyToManyField(blank=True, to='user.Modalidad')),
            ],
            options={
                'ordering': ('fecha_evento', 'titulo', 'pk'),
            },
        ),
    ]
