# Generated by Django 3.1.3 on 2021-02-06 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='hora_evento',
            field=models.TimeField(null=True, verbose_name='Hora del evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='link_conferencia',
            field=models.URLField(blank=True, verbose_name='Url de la conferencia'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='aforo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)], verbose_name='Aforo del evento'),
        ),
    ]
