# Generated by Django 3.1.3 on 2021-02-11 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0002_auto_20210206_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='usuarios_activos',
            field=models.ManyToManyField(blank=True, related_name='activos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=models.ImageField(default='default_eventos.png', upload_to='', verbose_name='Foto del evento'),
        ),
    ]
