# Generated by Django 3.1.3 on 2021-02-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_invitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion',
            name='token',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Token'),
        ),
    ]
