# Generated by Django 3.1.3 on 2021-03-08 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0008_auto_20210215_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='remitente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=models.ImageField(default='default_eventos.jpg', upload_to='', verbose_name='Foto del evento'),
        ),
    ]
