# Generated by Django 3.1.3 on 2021-03-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_auto_20210308_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento_comentario', to='eventos.evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='comentarios',
            field=models.ManyToManyField(blank=True, related_name='comentarios_evento', to='eventos.Comentario'),
        ),
    ]
