# Generated by Django 3.1.3 on 2021-03-15 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0010_auto_20210310_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='leidos',
            field=models.ManyToManyField(blank=True, related_name='lectores', to=settings.AUTH_USER_MODEL),
        ),
    ]
