# Generated by Django 3.1.3 on 2021-02-05 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticion',
            name='estado',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Estado'),
        ),
    ]
