# Generated by Django 3.1.3 on 2020-12-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mago',
            name='foto_perfil',
            field=models.FileField(default='default.png', upload_to='', verbose_name='Foto de perfil'),
        ),
    ]
