# Generated by Django 3.1.3 on 2020-12-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201211_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mago',
            name='foto_perfil',
            field=models.ImageField(default='default.png', upload_to='', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='mago',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Numero de teléfono'),
        ),
    ]
