# Generated by Django 3.1.3 on 2020-12-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201211_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mago',
            old_name='foto_perfil',
            new_name='foto',
        ),
    ]
