# Generated by Django 3.1.3 on 2020-12-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201212_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mago',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Descripción'),
        ),
    ]
