# Generated by Django 3.1.3 on 2020-12-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201212_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mago',
            name='modalidades',
            field=models.ManyToManyField(blank=True, to='user.Modalidad'),
        ),
    ]
