# Generated by Django 3.1.3 on 2021-04-07 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacion', '0001_initial'),
        ('user', '0009_mago_localizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mago',
            name='localizacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localizacion_usuario', to='localizacion.localizacion'),
        ),
    ]
