# Generated by Django 3.1.3 on 2021-01-10 17:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.TextField(verbose_name='Estado')),
                ('estado', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)], verbose_name='Estado')),
                ('fecha', models.DateField(verbose_name='Fecha de creación')),
                ('destinatario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatario_mensaje', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remitente_mensaje', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('fecha',),
            },
        ),
    ]
