# Generated by Django 3.1.3 on 2021-01-31 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_auto_20210111_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ('estado', '-fecha', '-id')},
        ),
    ]
