# Generated by Django 3.1.3 on 2021-02-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0003_auto_20210131_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ('estado', '-fecha', '-pk')},
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='cuerpo',
            field=models.TextField(max_length=1500, verbose_name='Cuerpo'),
        ),
    ]
